application:
  port: 8000
database:
  #host: "localhost" # use this when docker host is linux
  host: "host.docker.internal" # use this when docker host is not linux (ie. developing on MacOS)
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
